"""Initial migration

Revision ID: 7333df0b7629
Revises: 
Create Date: 2024-06-11 10:09:29.403905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7333df0b7629'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Broadcast',
    sa.Column('BroadcastID', sa.Integer(), nullable=False),
    sa.Column('MobileNo', sa.String(length=50), nullable=True),
    sa.Column('MessageType', sa.String(length=50), nullable=True),
    sa.Column('Message', sa.String(length=1000), nullable=True),
    sa.Column('CategoryID', sa.Integer(), nullable=True),
    sa.Column('SendNow', sa.String(length=1), nullable=True),
    sa.Column('TxReference', sa.String(length=50), nullable=True),
    sa.Column('ReceiverName', sa.String(length=200), nullable=True),
    sa.Column('VA_No', sa.String(length=20), nullable=True),
    sa.Column('MarketingName', sa.String(length=200), nullable=True),
    sa.Column('OS_Premium', sa.Numeric(), nullable=True),
    sa.Column('ConfirmDate', sa.DateTime(), nullable=True),
    sa.Column('DueDate', sa.DateTime(), nullable=True),
    sa.Column('BroadcastDate', sa.DateTime(), nullable=True),
    sa.Column('AsOfDate', sa.DateTime(), nullable=True),
    sa.Column('DateOfBirthday', sa.DateTime(), nullable=True),
    sa.Column('InsuredNameQQ', sa.String(length=255), nullable=True),
    sa.Column('InsuredName', sa.String(length=255), nullable=True),
    sa.Column('LineOfBusiness', sa.String(length=30), nullable=True),
    sa.Column('ObjectOfInsured', sa.String(length=200), nullable=True),
    sa.Column('ExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('PolicyNo', sa.String(length=50), nullable=True),
    sa.Column('PackageName', sa.String(length=255), nullable=True),
    sa.Column('ProductTypePlan', sa.String(length=255), nullable=True),
    sa.Column('Destination', sa.String(length=255), nullable=True),
    sa.Column('GrossPremium', sa.Numeric(), nullable=True),
    sa.Column('EffectiveDate', sa.DateTime(), nullable=True),
    sa.Column('PeriodPolicy', sa.String(length=50), nullable=True),
    sa.Column('Coverage', sa.String(length=200), nullable=True),
    sa.Column('AdditionalCoverage', sa.String(length=200), nullable=True),
    sa.Column('AdditionalCoverage2', sa.String(length=200), nullable=True),
    sa.Column('AdditionalCoverage3', sa.String(length=200), nullable=True),
    sa.Column('AdditionalCoverage4', sa.String(length=200), nullable=True),
    sa.Column('AdditionalCoverage5', sa.String(length=200), nullable=True),
    sa.Column('TemplateName', sa.String(length=100), nullable=True),
    sa.Column('NameSpace', sa.String(length=100), nullable=True),
    sa.Column('T', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('BroadcastID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Broadcast')
    # ### end Alembic commands ###
